blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/babyico/{repositry}/discussions
    about: Start a discussion, ask and answer questions here.
  - name: Discord support server
    url: https://discord.gg/EXHhWpb5ps
    about: The best place to go for help installing or using Iconical's games and softwares.
